BEGIN;

-- 1. Usuario
CREATE TABLE usuario (
  id_usuario       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre           VARCHAR(50)  NOT NULL,
  ap1              VARCHAR(50)  NOT NULL,
  ap2              VARCHAR(50),
  email            VARCHAR(100) NOT NULL UNIQUE,
  contraseña       VARCHAR(255) NOT NULL,
  tipo_usuario     VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
  fecha_nacimiento DATE         NOT NULL,
  CONSTRAINT chk_usuario_tipo
    CHECK (tipo_usuario IN ('NORMAL', 'ADMIN'))
);

-- 2. Trabajador
CREATE TABLE trabajador (
  dni    VARCHAR(10)   PRIMARY KEY,
  nombre VARCHAR(50)   NOT NULL,
  ap1    VARCHAR(50)   NOT NULL,
  ap2    VARCHAR(50),
  cargo  VARCHAR(50)   NOT NULL,
  sueldo NUMERIC(10,2) NOT NULL DEFAULT 1500.00,
  CONSTRAINT chk_trabajador_sueldo
    CHECK (sueldo >= 0)
);

-- 3. Monitor (especialización de Trabajador)
CREATE TABLE monitor (
  dni          VARCHAR(10) PRIMARY KEY,
  especialidad VARCHAR(50) NOT NULL,
  CONSTRAINT fk_monitor_trabajador
    FOREIGN KEY (dni) REFERENCES trabajador(dni)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- 4. Limpieza (especialización de Trabajador)
CREATE TABLE limpieza (
  dni VARCHAR(10) PRIMARY KEY,
  CONSTRAINT fk_limpieza_trabajador
    FOREIGN KEY (dni) REFERENCES trabajador(dni)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- 5. Sala
CREATE TABLE sala (
  id_sala INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre  VARCHAR(50) NOT NULL UNIQUE
);

-- 6. Clase
CREATE TABLE clase (
  nombre        VARCHAR(50) PRIMARY KEY,
  duracion      INTEGER     NOT NULL DEFAULT 50,
  clasificacion VARCHAR(50) NOT NULL DEFAULT 'General',
  CONSTRAINT chk_clase_duracion
    CHECK (duracion > 0)
);

-- 7. Producto
CREATE TABLE producto (
  id_producto      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre           VARCHAR(50)   NOT NULL,
  descripcion      VARCHAR(255),
  precio           NUMERIC(10,2) NOT NULL,
  stock_disponible INTEGER       NOT NULL DEFAULT 0,
  CONSTRAINT chk_producto_precio
    CHECK (precio >= 0),
  CONSTRAINT chk_producto_stock
    CHECK (stock_disponible >= 0)
);

-- 8. Sesion
CREATE TABLE sesion (
  id_sesion    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sala      INTEGER     NOT NULL,
  nombre_clase VARCHAR(50) NOT NULL,
  fecha_sesion DATE        NOT NULL,
  hora_inicio  TIME        NOT NULL,
  CONSTRAINT fk_sesion_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_sesion_clase
    FOREIGN KEY (nombre_clase) REFERENCES clase(nombre)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT uq_sesion_exacta
    UNIQUE (id_sala, fecha_sesion, hora_inicio)
);

-- 9. Reserva
CREATE TABLE reserva (
  id_reserva    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario    INTEGER NOT NULL,
  id_sesion     INTEGER NOT NULL,
  fecha_reserva DATE    NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT fk_reserva_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_reserva_sesion
    FOREIGN KEY (id_sesion) REFERENCES sesion(id_sesion)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT uq_reserva_usuario_sesion
    UNIQUE (id_usuario, id_sesion)
);

-- 10. Plaza (entidad débil de Sala)
CREATE TABLE plaza (
  id_plaza   INTEGER NOT NULL,
  id_sala    INTEGER NOT NULL,
  id_reserva INTEGER,                    -- NULL => plaza libre
  PRIMARY KEY (id_plaza, id_sala),
  CONSTRAINT fk_plaza_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_plaza_reserva
    FOREIGN KEY (id_reserva) REFERENCES reserva(id_reserva)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT chk_plaza_id
    CHECK (id_plaza > 0)
);

-- 11. Equipo
CREATE TABLE equipo (
  id_maquina        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sala           INTEGER       NOT NULL,
  nombre            VARCHAR(50)   NOT NULL,
  precio            NUMERIC(10,2) NOT NULL,
  fecha_adquisicion DATE          NOT NULL,
  CONSTRAINT fk_equipo_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT chk_equipo_precio
    CHECK (precio >= 0)
);

-- 12. Valorar
CREATE TABLE valorar (
  nombre_clase VARCHAR(50) NOT NULL,
  id_usuario   INTEGER     NOT NULL,
  fecha        DATE        NOT NULL DEFAULT CURRENT_DATE,
  opinion      VARCHAR(255),
  puntuacion   INTEGER     NOT NULL,
  PRIMARY KEY (nombre_clase, id_usuario, fecha),
  CONSTRAINT fk_valorar_clase
    FOREIGN KEY (nombre_clase) REFERENCES clase(nombre)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_valorar_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT chk_valorar_puntuacion
    CHECK (puntuacion BETWEEN 1 AND 5)
);

-- 13. Impartir (ternaria: Monitor–Sala–Clase)
CREATE TABLE impartir (
  dni_monitor  VARCHAR(10) NOT NULL,
  id_sala      INTEGER     NOT NULL,
  nombre_clase VARCHAR(50) NOT NULL,
  PRIMARY KEY (dni_monitor, id_sala, nombre_clase),
  CONSTRAINT fk_impartir_monitor
    FOREIGN KEY (dni_monitor) REFERENCES monitor(dni)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_impartir_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_impartir_clase
    FOREIGN KEY (nombre_clase) REFERENCES clase(nombre)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- 14. Trabajar (N:M Trabajador–Sala)
CREATE TABLE trabajar (
  dni_trabajador VARCHAR(10) NOT NULL,
  id_sala        INTEGER     NOT NULL,
  PRIMARY KEY (dni_trabajador, id_sala),
  CONSTRAINT fk_trabajar_trabajador
    FOREIGN KEY (dni_trabajador) REFERENCES trabajador(dni)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_trabajar_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- 15. PedirProducto (N:M Usuario–Producto)
CREATE TABLE pedir_producto (
  id_usuario  INTEGER NOT NULL,
  id_producto INTEGER NOT NULL,
  fecha       DATE    NOT NULL DEFAULT CURRENT_DATE,
  hora        TIME    NOT NULL DEFAULT LOCALTIME,
  cantidad    INTEGER NOT NULL,
  entregado   BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id_usuario, id_producto, fecha, hora),
  CONSTRAINT fk_pedir_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_pedir_producto
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT chk_pedir_cantidad
    CHECK (cantidad > 0)
);

-- ============================================================
-- ÍNDICES
-- ============================================================
CREATE INDEX idx_sesion_clase_fecha
  ON sesion (nombre_clase, fecha_sesion, hora_inicio);

CREATE INDEX idx_sesion_sala_fecha
  ON sesion (id_sala, fecha_sesion, hora_inicio);

CREATE INDEX idx_reserva_usuario
  ON reserva (id_usuario);

CREATE INDEX idx_reserva_sesion
  ON reserva (id_sesion);

CREATE INDEX idx_plaza_reserva
  ON plaza (id_reserva);

CREATE INDEX idx_plaza_sala
  ON plaza (id_sala);

CREATE INDEX idx_equipo_sala
  ON equipo (id_sala);

CREATE INDEX idx_pedir_usuario_entregado
  ON pedir_producto (id_usuario, entregado);

CREATE INDEX idx_valorar_clase
  ON valorar (nombre_clase);

-- ============================================================
-- TRIGGERS DE INTEGRIDAD
-- ============================================================

-- T1: Anti-solapamiento de sesiones en la misma sala
CREATE OR REPLACE FUNCTION fn_validar_solape_sesion()
RETURNS TRIGGER AS $$
DECLARE
  duracion_nueva INTEGER;
  inicio_nuevo   TIMESTAMP;
  fin_nuevo      TIMESTAMP;
BEGIN
  SELECT c.duracion INTO duracion_nueva
  FROM clase c
  WHERE c.nombre = NEW.nombre_clase;

  IF duracion_nueva IS NULL THEN
    RAISE EXCEPTION 'La clase % no existe o no tiene duración válida.', NEW.nombre_clase;
  END IF;

  inicio_nuevo := NEW.fecha_sesion::timestamp + NEW.hora_inicio;
  fin_nuevo    := inicio_nuevo + make_interval(mins => duracion_nueva);

  IF EXISTS (
    SELECT 1
    FROM sesion s
    JOIN clase c ON c.nombre = s.nombre_clase
    WHERE s.id_sala   = NEW.id_sala
      AND s.id_sesion <> COALESCE(NEW.id_sesion, -1)
      AND inicio_nuevo < (s.fecha_sesion::timestamp + s.hora_inicio
                          + make_interval(mins => c.duracion))
      AND (s.fecha_sesion::timestamp + s.hora_inicio) < fin_nuevo
  ) THEN
    RAISE EXCEPTION
      'No se puede insertar/actualizar la sesión: se solapa con otra en la misma sala.';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_solape_sesion
BEFORE INSERT OR UPDATE OF id_sala, nombre_clase, fecha_sesion, hora_inicio
ON sesion
FOR EACH ROW
EXECUTE FUNCTION fn_validar_solape_sesion();

-- T2: Herencia Disjunta — un trabajador no puede ser monitor Y limpieza
CREATE OR REPLACE FUNCTION fn_monitor_disjunto()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM limpieza WHERE dni = NEW.dni) THEN
    RAISE EXCEPTION
      'Un trabajador no puede pertenecer simultáneamente a monitor y limpieza.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_monitor_disjunto
BEFORE INSERT OR UPDATE OF dni ON monitor
FOR EACH ROW
EXECUTE FUNCTION fn_monitor_disjunto();

CREATE OR REPLACE FUNCTION fn_limpieza_disjunta()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM monitor WHERE dni = NEW.dni) THEN
    RAISE EXCEPTION
      'Un trabajador no puede pertenecer simultáneamente a limpieza y monitor.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_limpieza_disjunta
BEFORE INSERT OR UPDATE OF dni ON limpieza
FOR EACH ROW
EXECUTE FUNCTION fn_limpieza_disjunta();

-- T3: Herencia Total — todo trabajador debe tener subtipo
CREATE OR REPLACE FUNCTION fn_trabajador_debe_tener_subtipo()
RETURNS TRIGGER AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM monitor   WHERE dni = NEW.dni)
 AND NOT EXISTS (SELECT 1 FROM limpieza  WHERE dni = NEW.dni) THEN
    RAISE EXCEPTION
      'Todo trabajador debe pertenecer a una subclase: monitor o limpieza.';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER ctr_trabajador_debe_tener_subtipo
AFTER INSERT OR UPDATE OF dni ON trabajador
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_trabajador_debe_tener_subtipo();

-- T4: No dejar trabajador huérfano al borrar/mover subtipo
CREATE OR REPLACE FUNCTION fn_subtipo_no_puede_dejar_huerfano()
RETURNS TRIGGER AS $$
BEGIN
  IF EXISTS     (SELECT 1 FROM trabajador WHERE dni = OLD.dni)
 AND NOT EXISTS (SELECT 1 FROM monitor    WHERE dni = OLD.dni)
 AND NOT EXISTS (SELECT 1 FROM limpieza   WHERE dni = OLD.dni) THEN
    RAISE EXCEPTION 'No se puede dejar un trabajador sin subtipo.';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER ctr_monitor_no_huerfano
AFTER DELETE OR UPDATE OF dni ON monitor
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_subtipo_no_puede_dejar_huerfano();

CREATE CONSTRAINT TRIGGER ctr_limpieza_no_huerfano
AFTER DELETE OR UPDATE OF dni ON limpieza
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_subtipo_no_puede_dejar_huerfano();

COMMIT;