BEGIN;

-- 1. Usuario
CREATE TABLE usuario (
  id_usuario       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre           VARCHAR(50)  NOT NULL,
  ap1              VARCHAR(50)  NOT NULL,
  ap2              VARCHAR(50),
  email            VARCHAR(100) NOT NULL UNIQUE,
  contrasena       VARCHAR(255) NOT NULL,
  tipo_usuario     VARCHAR(20)  NOT NULL DEFAULT 'NORMAL',
  fecha_nacimiento DATE         NOT NULL,
  CONSTRAINT chk_usuario_tipo
    CHECK (tipo_usuario IN ('NORMAL', 'ADMIN'))
);

-- 2. Trabajador
CREATE TABLE trabajador (
  dni    VARCHAR(10)   PRIMARY KEY,
  nombre VARCHAR(50)   NOT NULL,
  ap1    VARCHAR(50)   NOT NULL,
  ap2    VARCHAR(50),
  cargo  VARCHAR(50)   NOT NULL,
  sueldo NUMERIC(10,2) NOT NULL DEFAULT 1500.00,
  CONSTRAINT chk_trabajador_sueldo
    CHECK (sueldo >= 0)
);

-- 3. Monitor (especialización de Trabajador)
CREATE TABLE monitor (
  dni          VARCHAR(10) PRIMARY KEY,
  especialidad VARCHAR(50) NOT NULL,
  CONSTRAINT fk_monitor_trabajador
    FOREIGN KEY (dni) REFERENCES trabajador(dni)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- 4. Limpieza (especialización de Trabajador)
CREATE TABLE limpieza (
  dni VARCHAR(10) PRIMARY KEY,
  CONSTRAINT fk_limpieza_trabajador
    FOREIGN KEY (dni) REFERENCES trabajador(dni)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- 5. Sala
CREATE TABLE sala (
  id_sala INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre  VARCHAR(50) NOT NULL UNIQUE
);

-- 6. Clase
CREATE TABLE clase (
  nombre        VARCHAR(50) PRIMARY KEY,
  duracion      INTEGER     NOT NULL DEFAULT 50,
  clasificacion VARCHAR(50) NOT NULL DEFAULT 'General',
  CONSTRAINT chk_clase_duracion
    CHECK (duracion > 0)
);

-- 7. Producto
CREATE TABLE producto (
  id_producto      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre           VARCHAR(50)   NOT NULL,
  descripcion      VARCHAR(255),
  precio           NUMERIC(10,2) NOT NULL,
  stock_disponible INTEGER       NOT NULL DEFAULT 0,
  CONSTRAINT chk_producto_precio
    CHECK (precio >= 0),
  CONSTRAINT chk_producto_stock
    CHECK (stock_disponible >= 0)
);

-- 8. Sesion
CREATE TABLE sesion (
  id_sesion    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sala      INTEGER     NOT NULL,
  nombre_clase VARCHAR(50) NOT NULL,
  dni_monitor  VARCHAR(10) NOT NULL,
  fecha_sesion DATE        NOT NULL,
  hora_inicio  TIME        NOT NULL,
  CONSTRAINT fk_sesion_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_sesion_clase
    FOREIGN KEY (nombre_clase) REFERENCES clase(nombre)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_sesion_monitor
    FOREIGN KEY (dni_monitor) REFERENCES monitor(dni)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT uq_sesion_exacta
    UNIQUE (id_sala, fecha_sesion, hora_inicio)
);

-- 9. Reserva
CREATE TABLE reserva (
  id_reserva    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario    INTEGER NOT NULL,
  id_sesion     INTEGER NOT NULL,
  fecha_reserva DATE    NOT NULL DEFAULT CURRENT_DATE,
  CONSTRAINT fk_reserva_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_reserva_sesion
    FOREIGN KEY (id_sesion) REFERENCES sesion(id_sesion)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT uq_reserva_usuario_sesion
    UNIQUE (id_usuario, id_sesion)
);

-- 10. Plaza (entidad débil de Sala)
CREATE TABLE plaza (
  id_plaza   INTEGER NOT NULL,
  id_sala    INTEGER NOT NULL,
  PRIMARY KEY (id_plaza, id_sala),
  CONSTRAINT fk_plaza_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT chk_plaza_id
    CHECK (id_plaza > 0)
);

-- 11. Reserva_Plaza (asociativa entre Reserva y Plaza)
CREATE TABLE reserva_plaza (
  id_reserva INTEGER NOT NULL,
  id_sesion  INTEGER NOT NULL,
  id_sala    INTEGER NOT NULL,
  id_plaza   INTEGER NOT NULL,
  PRIMARY KEY (id_reserva, id_sala, id_plaza),
  CONSTRAINT fk_reserva_plaza_reserva
    FOREIGN KEY (id_reserva) REFERENCES reserva(id_reserva)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_reserva_plaza_sesion
    FOREIGN KEY (id_sesion) REFERENCES sesion(id_sesion)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_reserva_plaza_plaza
    FOREIGN KEY (id_plaza, id_sala) REFERENCES plaza(id_plaza, id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT uq_plaza_por_sesion
    UNIQUE (id_sesion, id_sala, id_plaza)
);

-- 13. Equipo
CREATE TABLE equipo (
  id_maquina        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sala           INTEGER       NOT NULL,
  nombre            VARCHAR(50)   NOT NULL,
  precio            NUMERIC(10,2) NOT NULL,
  fecha_adquisicion DATE          NOT NULL,
  CONSTRAINT fk_equipo_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT chk_equipo_precio
    CHECK (precio >= 0)
);

-- 14. Valorar
CREATE TABLE valorar (
  nombre_clase VARCHAR(50) NOT NULL,
  id_usuario   INTEGER     NOT NULL,
  fecha        DATE        NOT NULL DEFAULT CURRENT_DATE,
  opinion      VARCHAR(255),
  puntuacion   INTEGER     NOT NULL,
  PRIMARY KEY (nombre_clase, id_usuario, fecha),
  CONSTRAINT fk_valorar_clase
    FOREIGN KEY (nombre_clase) REFERENCES clase(nombre)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_valorar_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT chk_valorar_puntuacion
    CHECK (puntuacion BETWEEN 1 AND 5)
);

-- 15. Impartir (ternaria: Monitor–Sala–Clase)
CREATE TABLE impartir (
  dni_monitor  VARCHAR(10) NOT NULL,
  id_sala      INTEGER     NOT NULL,
  nombre_clase VARCHAR(50) NOT NULL,
  PRIMARY KEY (dni_monitor, id_sala, nombre_clase),
  CONSTRAINT fk_impartir_monitor
    FOREIGN KEY (dni_monitor) REFERENCES monitor(dni)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_impartir_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_impartir_clase
    FOREIGN KEY (nombre_clase) REFERENCES clase(nombre)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- 16. Trabajar (N:M Trabajador–Sala)
CREATE TABLE trabajar (
  dni_trabajador VARCHAR(10) NOT NULL,
  id_sala        INTEGER     NOT NULL,
  PRIMARY KEY (dni_trabajador, id_sala),
  CONSTRAINT fk_trabajar_trabajador
    FOREIGN KEY (dni_trabajador) REFERENCES trabajador(dni)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_trabajar_sala
    FOREIGN KEY (id_sala) REFERENCES sala(id_sala)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

-- 17. PedirProducto (N:M Usuario–Producto)
CREATE TABLE pedir_producto (
  id_usuario  INTEGER NOT NULL,
  id_producto INTEGER NOT NULL,
  fecha       DATE    NOT NULL DEFAULT CURRENT_DATE,
  hora        TIME    NOT NULL DEFAULT LOCALTIME,
  cantidad    INTEGER NOT NULL,
  entregado   BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id_usuario, id_producto, fecha, hora),
  CONSTRAINT fk_pedir_usuario
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_pedir_producto
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT chk_pedir_cantidad
    CHECK (cantidad > 0)
);

-- ============================================================
-- ÍNDICES
-- ============================================================
CREATE INDEX idx_sesion_clase_fecha
  ON sesion (nombre_clase, fecha_sesion, hora_inicio);

CREATE INDEX idx_sesion_sala_fecha
  ON sesion (id_sala, fecha_sesion, hora_inicio);

CREATE INDEX idx_reserva_usuario
  ON reserva (id_usuario);

CREATE INDEX idx_reserva_sesion
  ON reserva (id_sesion);

CREATE INDEX idx_plaza_sala
  ON plaza (id_sala);

CREATE INDEX idx_reserva_plaza_sesion
  ON reserva_plaza (id_sesion);

CREATE INDEX idx_reserva_plaza_reserva
  ON reserva_plaza (id_reserva);

CREATE INDEX idx_reserva_plaza_plaza
  ON reserva_plaza (id_sala, id_plaza);

CREATE INDEX idx_equipo_sala
  ON equipo (id_sala);

CREATE INDEX idx_pedir_usuario_entregado
  ON pedir_producto (id_usuario, entregado);

CREATE INDEX idx_valorar_clase
  ON valorar (nombre_clase);

-- ============================================================
-- TRIGGERS DE INTEGRIDAD
-- ============================================================

-- Restricción: validar que la plaza reservada corresponde a la sesión y sala de la reserva
CREATE OR REPLACE FUNCTION fn_validar_reserva_plaza()
RETURNS TRIGGER AS $$
DECLARE
  sesion_reserva INTEGER;
  sala_sesion    INTEGER;
BEGIN
  SELECT r.id_sesion
  INTO sesion_reserva
  FROM reserva r
  WHERE r.id_reserva = NEW.id_reserva;

  IF sesion_reserva IS NULL THEN
    RAISE EXCEPTION 'La reserva % no existe.', NEW.id_reserva;
  END IF;

  IF sesion_reserva <> NEW.id_sesion THEN
    RAISE EXCEPTION 'La plaza reservada no corresponde a la sesión de la reserva.';
  END IF;

  SELECT s.id_sala
  INTO sala_sesion
  FROM sesion s
  WHERE s.id_sesion = NEW.id_sesion;

  IF sala_sesion IS NULL THEN
    RAISE EXCEPTION 'La sesión % no existe.', NEW.id_sesion;
  END IF;

  IF sala_sesion <> NEW.id_sala THEN
    RAISE EXCEPTION 'La plaza seleccionada no pertenece a la sala de la sesión.';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_validar_reserva_plaza
BEFORE INSERT OR UPDATE
ON reserva_plaza
FOR EACH ROW
EXECUTE FUNCTION fn_validar_reserva_plaza();

COMMIT;